name: thunder
description: An open-source cross-platform Lemmy client for iOS and Android built with Flutter
publish_to: none
version: "0.6.0-3+69"

environment:
  sdk: "^3.0.0"
  flutter: ">=3.10.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  push:
    path: packages/push/push
  lemmy_api_client:
    git:
      url: "https://github.com/gwbischof/lemmy_api_client.git"
      ref: 2886218a71c75d14cb21d2079bfb3666603d3221
      #url: "https://github.com/thunder-app/lemmy_api_client.git"
      #ref: 16d14a1c13ac9522e85188ad9cf23d8912ec8fee
  link_preview_generator:
    git:
      url: "https://github.com/thunder-app/link_preview_generator.git"
      ref: 77a00003216591c32194c2af3c4fc1cf64797e53
  markdown_editor:
    git:
      url: "https://github.com/thunder-app/markdown-editor.git"
      ref: 514e3718a42d4398619d66b6ac1ccd53bafd9b3f
  xayn_readability:
    git:
      url: https://github.com/xaynetwork/xayn_readability
  android_intent_plus: "^5.0.1"
  app_links: "^6.3.2"
  auto_size_text: "^3.0.0"
  back_button_interceptor: ^8.0.0
  background_fetch: "^1.2.1"
  bloc: "^8.1.2"
  bloc_concurrency: "^0.2.2"
  cached_network_image: "^3.2.3"
  collection: "^1.17.0"
  connectivity_plus: "^6.0.2"
  dart_ping: "^9.0.0"
  dart_ping_ios: "^4.0.0"
  device_info_plus: ^11.1.1
  drift: "^2.21.0"
  drift_flutter: "^0.2.1"
  dynamic_color: "^1.6.5"
  equatable: "^2.0.5"
  expandable: "^5.0.1"
  extended_image: ^9.0.7
  fading_edge_scrollview: "^4.1.1"
  flex_color_scheme: "^8.0.0"
  flutter_bloc: "^8.1.3"
  flutter_cache_manager: "^3.3.0"
  flutter_custom_tabs: "^2.0.0-beta.1"
  flutter_displaymode: "^0.6.0"
  flutter_file_dialog: "^3.0.2"
  flutter_keyboard_visibility: "^6.0.0"
  flutter_local_notifications: ^18.0.1
  flutter_markdown: "^0.7.3+1"
  flutter_native_splash: "^2.3.1"
  flutter_sharing_intent: "^1.1.1"
  flutter_staggered_grid_view: "^0.7.0"
  flutter_typeahead: "^5.2.0"
  gal: "^2.2.0"
  html: "^0.15.4"
  html_unescape: "^2.0.0"
  http: ^1.2.2
  image_picker: "^1.0.0"
  intl: "^0.19.0"
  jovial_svg: "^1.1.19"
  l10n_esperanto: "^2.0.9"
  markdown: "^7.2.2"
  overlay_support: "^2.1.0"
  path: "^1.8.3"
  path_provider: "^2.0.15"
  permission_handler: "^11.0.0"
  screenshot: "^3.0.0"
  share_plus: "^10.0.2"
  shared_preferences: "^2.1.2"
  sliver_tools: "^0.2.12"
  smooth_highlight: "^0.1.1"
  stream_transform: "^2.1.0"
  super_sliver_list: "^0.4.1"
  swipeable_page_route: "^0.4.0"
  unifiedpush: "^5.0.1"
  url_launcher: "^6.1.11"
  # There is an intentional space between the packge name and colon below. Do not remove!
  version : "^3.0.2"
  video_player: "^2.9.2"
  visibility_detector: "^0.4.0+2"
  webview_flutter: "^4.2.2"
  webview_flutter_android: ^4.1.0
  webview_flutter_wkwebview: "^3.5.0"
  youtube_player_flutter: "^9.1.0"
  youtube_player_iframe: "^5.2.0"
  freezed_annotation: ^2.4.4
  flutter_web_auth_2: ^4.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^2.4.13"
  drift_dev: "^2.21.2"
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^5.0.0
  sqflite: "^2.4.0"
  sqflite_common_ffi: "^2.3.4"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/logo.png"
    - "assets/logo_monochrome.png"
    - "assets/logo_android.png"
    - "assets/logo_android_background.png"
    - "assets/logo_android_monochrome.png"
  fonts:
    - family: Thunder
      fonts:
        - asset: "fonts/Thunder.ttf"

flutter_native_splash:
  image: assets/logo.png
  color: 212123
